(function(){'use strict';function n(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function q(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=q(this);function t(a,b){if(b)a:{var c=r;a=a.split(".");for(var h=0;h<a.length-1;h++){var g=a[h];if(!(g in c))break a;c=c[g]}a=a[a.length-1];h=c[a];b=b(h);b!=h&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
t("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(h+(k||"")+"_"+g++,k)}function c(k,m){this.g=k;p(this,"description",{configurable:!0,writable:!0,value:m})}if(a)return a;c.prototype.toString=function(){return this.g};var h="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var h=r[b[c]];"function"===typeof h&&"function"!=typeof h.prototype[a]&&p(h.prototype,a,{configurable:!0,writable:!0,value:function(){return v(n(this))}})}return a});function v(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(d){this.g=(f+=Math.random()+1).toString();if(d){d=w(d);for(var e;!(e=d.next()).done;)e=e.value,this.set(e[0],e[1])}}function c(){}function h(d){var e=typeof d;return"object"===e&&null!==d||"function"===e}function g(d){if(!x(d,m)){var e=new c;p(d,m,{value:e})}}function k(d){var e=Object[d];e&&(Object[d]=function(l){if(l instanceof c)return l;Object.isExtensible(l)&&g(l);return e(l)})}if(function(){if(!a||!Object.seal)return!1;try{var d=Object.seal({}),e=Object.seal({}),
l=new a([[d,2],[e,3]]);if(2!=l.get(d)||3!=l.get(e))return!1;l.delete(d);l.set(e,4);return!l.has(d)&&4==l.get(e)}catch(u){return!1}}())return a;var m="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var f=0;b.prototype.set=function(d,e){if(!h(d))throw Error("Invalid WeakMap key");g(d);if(!x(d,m))throw Error("WeakMap key fail: "+d);d[m][this.g]=e;return this};b.prototype.get=function(d){return h(d)&&x(d,m)?d[m][this.g]:void 0};b.prototype.has=function(d){return h(d)&&x(d,
m)&&x(d[m],this.g)};b.prototype.delete=function(d){return h(d)&&x(d,m)&&x(d[m],this.g)?delete d[m][this.g]:!1};return b});
t("Map",function(a){function b(){var f={};return f.i=f.next=f.head=f}function c(f,d){var e=f[1];return v(function(){if(e){for(;e.head!=f[1];)e=e.i;for(;e.next!=e.head;)return e=e.next,{done:!1,value:d(e)};e=null}return{done:!0,value:void 0}})}function h(f,d){var e=d&&typeof d;"object"==e||"function"==e?k.has(d)?e=k.get(d):(e=""+ ++m,k.set(d,e)):e="p_"+d;var l=f[0][e];if(l&&x(f[0],e))for(f=0;f<l.length;f++){var u=l[f];if(d!==d&&u.key!==u.key||d===u.key)return{id:e,list:l,index:f,h:u}}return{id:e,list:l,
index:-1,h:void 0}}function g(f){this[0]={};this[1]=b();this.size=0;if(f){f=w(f);for(var d;!(d=f.next()).done;)d=d.value,this.set(d[0],d[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),d=new a(w([[f,"s"]]));if("s"!=d.get(f)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var e=d.entries(),l=e.next();if(l.done||l.value[0]!=f||"s"!=l.value[1])return!1;l=e.next();return l.done||4!=l.value[0].x||
"t"!=l.value[1]||!e.next().done?!1:!0}catch(u){return!1}}())return a;var k=new WeakMap;g.prototype.set=function(f,d){f=0===f?0:f;var e=h(this,f);e.list||(e.list=this[0][e.id]=[]);e.h?e.h.value=d:(e.h={next:this[1],i:this[1].i,head:this[1],key:f,value:d},e.list.push(e.h),this[1].i.next=e.h,this[1].i=e.h,this.size++);return this};g.prototype.delete=function(f){f=h(this,f);return f.h&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.h.i.next=f.h.next,f.h.next.i=f.h.i,f.h.head=null,
this.size--,!0):!1};g.prototype.clear=function(){this[0]={};this[1]=this[1].i=b();this.size=0};g.prototype.has=function(f){return!!h(this,f).h};g.prototype.get=function(f){return(f=h(this,f).h)&&f.value};g.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};g.prototype.keys=function(){return c(this,function(f){return f.key})};g.prototype.values=function(){return c(this,function(f){return f.value})};g.prototype.forEach=function(f,d){for(var e=this.entries(),l;!(l=e.next()).done;)l=
l.value,f.call(d,l[1],l[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var m=0;return g});
t("Set",function(a){function b(c){this.g=new Map;if(c){c=w(c);for(var h;!(h=c.next()).done;)this.add(h.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),h=new a(w([c]));if(!h.has(c)||1!=h.size||h.add(c)!=h||1!=h.size||h.add({x:4})!=h||2!=h.size)return!1;var g=h.entries(),k=g.next();if(k.done||k.value[0]!=c||k.value[1]!=c)return!1;k=g.next();return k.done||k.value[0]==c||4!=k.value[0].x||
k.value[1]!=k.value[0]?!1:g.next().done}catch(m){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,h){var g=this;this.g.forEach(function(k){return c.call(h,k,k,g)})};return b});t("Object.entries",function(a){return a?a:function(b){var c=[],h;for(h in b)x(b,h)&&c.push([h,b[h]]);return c}});t("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
t("Array.prototype.includes",function(a){return a?a:function(b,c){var h=this;h instanceof String&&(h=String(h));var g=h.length;c=c||0;for(0>c&&(c=Math.max(c+g,0));c<g;c++){var k=h[c];if(k===b||Object.is(k,b))return!0}return!1}});
t("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var y=this||self;function z(){var a=void 0===a?y:a;return a.oneAfmaInstance};function A(){var a=this;this.o=new Set;this.l=B();this.m=C();this.j=this.g=!1;var b=z();this.g=b?b.visibilityState:!0;D(this);b=window.AFMA_Communicator;null==b||b.addEventListener("onshow",function(){a.g=!0;E(a)});null==b||b.addEventListener("onhide",function(){a.g=!1;E(a)});var c;null==(c=F)||c.addEventListener("visibilitychange",function(){a.l=B();E(a)});var h;null==(h=G)||h.addEventListener("resize",function(){a.m=C();E(a)})}function B(){var a=F;return a&&"visible"===a.visibilityState}
function C(){var a=G;return a&&0<a.innerWidth&&0<a.innerHeight}function D(a){var b=a.g&&a.l&&a.m;if(a.j===b)return!1;a.j=b;return!0}function E(a){if(D(a))for(var b=w(a.o),c=b.next();!c.done;c=b.next())c=c.value,c(a.j)}function H(a){var b=I||(I=new A);a(b.j);b.o.add(a)}var F=document,G=window,I;function J(){(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}J.prototype.setAttribute=function(a,b){this.g&&window.mys.pingback.setAttribute(a,b)};J.prototype.setData=function(a,b){this.g&&window.mys.pingback.setData(a,b,4)};J.prototype.send=function(a){this.g&&window.mys.pingback.send(a)};function K(){var a=this;this.body=L;this.pingback=new J;this.j={};var b={};this.m=(b.overallStart=function(){return void M(a,3)},b.overallReady=function(){return void M(a,4)},b.overallQuiet=function(){return void M(a,5)},b.overallError=function(){return void M(a,6)},b.assembleStart=function(){return void N(a,7)},b.assembleReady=function(){return void O(a,7)},b.decorateStart=function(){return void N(a,8)},b.decorateReady=function(){return void O(a,8)},b.fontStart=function(){return void N(a,9)},b.fontReady=
function(){return void O(a,9)},b.spanStart=function(){return void N(a,10)},b.spanReady=function(){return void O(a,10)},b.prepareStart=function(){return void N(a,11)},b.prepareReady=function(){return void O(a,11)},b.bindingStart=function(){return void N(a,12)},b.bindingReady=function(){return void O(a,12)},b.browserStart=function(){return void N(a,13)},b.browserStartEnd=function(){return void O(a,13)},b.browserReady=function(){return void N(a,14)},b.browserReadyEnd=function(){return void O(a,14)},
b.browserQuiet=function(){return void N(a,15)},b.browserQuietEnd=function(){return void O(a,15)},b);this.g=[23];this.l=[24]}
function M(a,b){var c;if((a.g.includes(b)||a.l.includes(b))&&(null==(c=window.performance)?0:c.getEntries)&&window.PerformanceNavigationTiming&&window.PerformanceResourceTiming){c=a.g.includes(b)?["script"]:[];var h=window.performance.getEntries(),g=0,k=0,m=0,f=0;h=w(h);for(var d=h.next();!d.done;d=h.next()){var e=d.value;e.name.includes("pagead2.googlesyndication.com/pagead/gen_204?id=mys")||(e instanceof window.PerformanceNavigationTiming?g+=e.transferSize||0:e instanceof window.PerformanceResourceTiming&&
(d=e.initiatorType,e=e.transferSize||0,0===c.length||c.includes(d))&&(m++,k+=0===e?1:0,f+=e))}a.g.includes(b)?(a.pingback.setData(16,g),a.pingback.setData(17,f),a.pingback.setData(18,m),a.pingback.setData(19,k)):a.l.includes(b)&&(a.pingback.setData(20,f),a.pingback.setData(21,m),a.pingback.setData(22,k))}a.pingback.setData(b,window.performance.now());a.pingback.send()}function N(a,b){a.j[b]=window.performance.now()}
function O(a,b){a.j.hasOwnProperty(b)&&(a.pingback.setData(b,window.performance.now()-a.j[b]),13===b&&(a.pingback.setData(30,window.innerWidth+"x"+window.innerHeight),b=a.body,a.pingback.setData(25,b.clientWidth+"x"+b.clientHeight)),a.pingback.send())};var L=document.getElementById("mys-content");
(function(){var a=new K,b;if(null!=(b=window.mys)&&b.pingback){window.addEventListener("error",function(g){a.pingback.setData(1,g.message);a.pingback.setData(95,g.filename);a.pingback.send()});a.body.addEventListener("customError",function(g){var k="custom_error: ";g.detail&&(k+=g.detail.message);a.pingback.setData(2,k);a.pingback.send()});window.addEventListener("click",function(g){var k=Date.now()-window.mys.pingback.getBaseTime();a.pingback.setData(47,g.clientX+"x"+g.clientY+"@"+k);a.pingback.send()},
!0);var c;if(null!=(c=window.performance)&&c.now)for(window.addEventListener("DOMContentLoaded",function(){return void M(a,23)}),window.addEventListener("load",function(){M(a,24);setTimeout(function(){var g;null!=(g=window.performance)&&g.getEntriesByType&&(g=performance.getEntriesByType("navigation")[0])&&(a.pingback.setData(50,g.fetchStart),a.pingback.setData(51,g.domainLookupStart),a.pingback.setData(52,g.domainLookupEnd),a.pingback.setData(53,g.connectStart),a.pingback.setData(54,g.connectEnd),
a.pingback.setData(55,g.secureConnectionStart),a.pingback.setData(56,g.requestStart),a.pingback.setData(57,g.responseStart),a.pingback.setData(58,g.responseEnd),a.pingback.setData(59,g.domInteractive),a.pingback.setData(60,g.domContentLoadedEventStart),a.pingback.setData(61,g.domContentLoadedEventEnd),a.pingback.setData(62,g.domComplete),a.pingback.setData(63,g.loadEventStart),a.pingback.setData(64,g.loadEventEnd),a.pingback.send())},0)}),H(function(g){g?a.pingback.setData(75,window.performance.now()):
a.pingback.setData(76,window.performance.now());a.pingback.send()}),b=w(Object.entries(a.m)),c=b.next();!c.done;c=b.next()){var h=w(c.value);c=h.next().value;h=h.next().value;a.body.addEventListener(c,h)}}})();}).call(this);
